=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/dcconfig.dtd
<!--
        Data collection (DC) configuration DTD
        Date: November 20th 2009
        Version: 1.3
        Copyright (c) 2006,2007 Advanced Micro Devices, Inc. All rights reserved.

        This DTD checks the validity of CodeAnalyst data collection
        configuration XML files.
 -->

  <!ELEMENT dc_configuration (tbp|ebp)>
  <!ATTLIST dc_configuration cpu_type CDATA #REQUIRED>

  <!ELEMENT tbp (tool_tip,description)>
  <!ATTLIST tbp name            CDATA #REQUIRED>
  <!ATTLIST tbp interval        CDATA "1.0">

  <!ELEMENT ebp (tool_tip,description)>
  <!ATTLIST ebp name            CDATA #REQUIRED>
  <!ATTLIST ebp mux_period      CDATA "1">

  <!ELEMENT event EMPTY>
  <!ATTLIST event select       CDATA #REQUIRED>
  <!ATTLIST event mask         CDATA #REQUIRED>
  <!ATTLIST event os           CDATA #REQUIRED>
  <!ATTLIST event user         CDATA #REQUIRED>
  <!ATTLIST event count        CDATA #REQUIRED>
  <!ATTLIST event edge_detect  CDATA "F">

  <!ELEMENT tool_tip    (#PCDATA)>
  <!ELEMENT description (#PCDATA)>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/family14h/ibs_op_overall.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Instruction-based sampling (IBS) data collection configuration
         Date:    November 20th 2009
         Version: 1.0
         Processor: AMD family14h
         Copyright (c) 2009 Advanced Micro Devices, Inc. All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family14h">

  <ebp name="IBS Op Overall Assessment" mux_period="0">

	<event select="F100" mask="01" count="1000000"></event>
	<event select="F101" mask="01" count="1000000"></event>
	<event select="F102" mask="01" count="1000000"></event>
	<event select="F103" mask="01" count="1000000"></event>
	<event select="F200" mask="01" count="1000000"></event>

    <tool_tip>
      Get an overall assessment of performance using IBS Op
    </tool_tip>

    <description>
      Use this configuration to get an overall assesment of performance 
      using IBS Op.
    </description>

  </ebp>

</dc_configuration>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/K7/branch.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Analyze branch/near return prediction using event-based profiling
         Date:    11 June 2007
         Version: 1.1c
         Processor: AMD K7 family
         Copyright (c) 2007 Advanced Micro Devices, Inc. All rights reserved.
 -->

<dc_configuration cpu_type="i386/athlon">

  <ebp name="Investigate branching" mux_period="1">

      <event select="C0" mask="00" os="T" user="T" count="250000"></event>
      <event select="C2" mask="00" os="T" user="T" count="25000"></event>
      <event select="C3" mask="00" os="T" user="T" count="25000"></event>
      <event select="C4" mask="00" os="T" user="T" count="25000"></event>

    <tool_tip>
      Find mispredicted branches
    </tool_tip>

    <description>
      Use this configuration to find poorly predicted branches.
    </description>

  </ebp>

</dc_configuration>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/family12h/ibs_op_ls_expert.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Instruction-based sampling (IBS) data collection configuration
         Date:    November 20th 2009
         Version: 1.0
         Processor: AMD family12h
         Copyright (c) 2009 Advanced Micro Devices, Inc. All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family12h">

  <ebp name="IBS Op Load-Store (expert)" mux_period="0">

	<event select="F200" mask="01" count="1000000"></event>
	<event select="F201" mask="01" count="1000000"></event>
	<event select="F202" mask="01" count="1000000"></event>
	<event select="F209" mask="01" count="1000000"></event>
	<event select="F20A" mask="01" count="1000000"></event>
	<event select="F20B" mask="01" count="1000000"></event>
	<event select="F20C" mask="01" count="1000000"></event>
	<event select="F210" mask="01" count="1000000"></event>

    <tool_tip>
      Measure data load / store performance using IBS Op (expert)
    </tool_tip>

    <description>
      Use this configuration to measure data load / store performance 
      using IBS Op (expert).
    </description>

  </ebp>

</dc_configuration>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/GH/ibs_op_nb_service.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Instruction-based sampling (IBS) data collection configuration
         Date:    November 20th 2009
         Version: 1.1
         Processor: AMD family 10h
         Copyright (c) 2007 Advanced Micro Devices, Inc. All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family10">

  <ebp name="IBS Op Northbridge Services" mux_period="0">

	<event select="F201" mask="01" count="1000000"></event>
	<event select="F242" mask="01" count="1000000"></event>
	<event select="F243" mask="01" count="1000000"></event>
	<event select="F244" mask="01" count="1000000"></event>
	<event select="F245" mask="01" count="1000000"></event>
	<event select="F246" mask="01" count="1000000"></event>
	<event select="F247" mask="01" count="1000000"></event>
	<event select="F248" mask="01" count="1000000"></event>

    <tool_tip>
      Measure northbridge services performance using IBS Op
    </tool_tip>

    <description>
      Use this configuration to measure northbridge services performance 
      using IBS Op.
    </description>

  </ebp>

</dc_configuration>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/family14h/ibs_op_ls_page.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Instruction-based sampling (IBS) data collection configuration
         Date:    November 20th 2009
         Version: 1.0
         Processor: AMD family14h
         Copyright (c) 2009 Advanced Micro Devices, Inc. All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family14h">

  <ebp name="IBS Op Load-Store Page Size" mux_period="0">

	<event select="F200" mask="01" count="1000000"></event>
	<event select="F211" mask="01" count="1000000"></event>
	<event select="F212" mask="01" count="1000000"></event>
	<event select="F213" mask="01" count="1000000"></event>
	<event select="F215" mask="01" count="1000000"></event>
	<event select="F216" mask="01" count="1000000"></event>
	<event select="F217" mask="01" count="1000000"></event>

    <tool_tip>
      Measure data load / store page size performance using IBS Op
    </tool_tip>

    <description>
      Use this configuration to measure data load / store page size performance 
      using IBS Op.
    </description>

  </ebp>

</dc_configuration>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/family15h/ibs_op_ls.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Instruction-based sampling (IBS) data collection configuration
         Date:    28 June 2010
         Version: 1.1
         Processor: AMD family 15h
         Copyright (c) 2007-2010 Advanced Micro Devices, Inc.
                       All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family15h">

  <ebp name="IBS Op Load-Store" mux_period="0">

	<event select="F200" mask="01" count="1000000"></event>
	<event select="F201" mask="01" count="1000000"></event>
	<event select="F202" mask="01" count="1000000"></event>
	<event select="F206" mask="01" count="1000000"></event>
	<event select="F219" mask="01" count="1000000"></event>

    <tool_tip>
      Measure data load / store performance using IBS Op
    </tool_tip>

    <description>
      Use this configuration to measure data load / store performance 
      using IBS Op.
    </description>

  </ebp>

</dc_configuration>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/GH/ibs_op_branch.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Instruction-based sampling (IBS) data collection configuration
         Date:    November 20th 2009
         Version: 1.1
         Processor: AMD family 10h
         Copyright (c) 2007 Advanced Micro Devices, Inc. All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family10">

  <ebp name="IBS Op Branch" mux_period="0">

	<event select="F100" mask="01" count="1000000"></event>
	<event select="F101" mask="01" count="1000000"></event>
	<event select="F102" mask="01" count="1000000"></event>
	<event select="F103" mask="01" count="1000000"></event>
	<event select="F104" mask="01" count="1000000"></event>
	<event select="F105" mask="01" count="1000000"></event>
	<event select="F106" mask="01" count="1000000"></event>

    <tool_tip>
      Find mispredicted branches using IBS Op
    </tool_tip>

    <description>
      Use this configuration to find poorly predicted branches
      using IBS Op.
    </description>

  </ebp>

</dc_configuration>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/family14h/ibs_op_ls_memacc.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Instruction-based sampling (IBS) data collection configuration
         Date:    November 20th 2009
         Version: 1.0
         Processor: AMD family14h
         Copyright (c) 2009 Advanced Micro Devices, Inc. All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family14h">

  <ebp name="IBS Op Load-Store Memory Access" mux_period="0">

	<event select="F200" mask="01" count="1000000"></event>
	<event select="F201" mask="01" count="1000000"></event>
	<event select="F202" mask="01" count="1000000"></event>
	<event select="F20D" mask="01" count="1000000"></event>
	<event select="F20E" mask="01" count="1000000"></event>
	<event select="F20F" mask="01" count="1000000"></event>

    <tool_tip>
      Measure data load / store memory access performance using IBS Op
    </tool_tip>

    <description>
      Use this configuration to measure data load / store memory access 
      performance using IBS Op.
    </description>

  </ebp>

</dc_configuration>
