=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/dcconfig.dtd
<!--
        Data collection (DC) configuration DTD
        Date: November 20th 2009
        Version: 1.3
        Copyright (c) 2006,2007 Advanced Micro Devices, Inc. All rights reserved.

        This DTD checks the validity of CodeAnalyst data collection
        configuration XML files.
 -->

  <!ELEMENT dc_configuration (tbp|ebp)>
  <!ATTLIST dc_configuration cpu_type CDATA #REQUIRED>

  <!ELEMENT tbp (tool_tip,description)>
  <!ATTLIST tbp name            CDATA #REQUIRED>
  <!ATTLIST tbp interval        CDATA "1.0">

  <!ELEMENT ebp (tool_tip,description)>
  <!ATTLIST ebp name            CDATA #REQUIRED>
  <!ATTLIST ebp mux_period      CDATA "1">

  <!ELEMENT event EMPTY>
  <!ATTLIST event select       CDATA #REQUIRED>
  <!ATTLIST event mask         CDATA #REQUIRED>
  <!ATTLIST event os           CDATA #REQUIRED>
  <!ATTLIST event user         CDATA #REQUIRED>
  <!ATTLIST event count        CDATA #REQUIRED>
  <!ATTLIST event edge_detect  CDATA "F">

  <!ELEMENT tool_tip    (#PCDATA)>
  <!ELEMENT description (#PCDATA)>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/family12h/ibs_op_return.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Instruction-based sampling (IBS) data collection configuration
         Date:    November 20th 2009
         Version: 1.0
         Processor: AMD family12h
         Copyright (c) 2009 Advanced Micro Devices, Inc. All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family12h">

  <ebp name="IBS Op Return" mux_period="0">

	<event select="F100" mask="01" count="1000000"></event>
	<event select="F101" mask="01" count="1000000"></event>
	<event select="F102" mask="01" count="1000000"></event>
	<event select="F103" mask="01" count="1000000"></event>
	<event select="F107" mask="01" count="1000000"></event>
	<event select="F108" mask="01" count="1000000"></event>

    <tool_tip>
      Find mispredicted returns using IBS Op
    </tool_tip>

    <description>
      Use this configuration to find poorly predicted returns 
      using IBS Op.
    </description>

  </ebp>

</dc_configuration>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/GR/inst_access.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
        Analyze instruction fetch and ITLB behavior using event-based profiling
        Date:    20 February 2008
        Version: 1.2
        Processor: AMD family 11h
        Copyright (c) 2008 Advanced Micro Devices, Inc. All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family11h">

  <ebp name="Investigate instruction access" mux_period="1">

      <event select="C0" mask="00" os="T" user="T" count="250000"></event>
      <event select="80" mask="00" os="T" user="T" count="250000"></event>
      <event select="81" mask="00" os="T" user="T" count="25000"></event>
      <event select="84" mask="00" os="T" user="T" count="25000"></event>
      <event select="85" mask="00" os="T" user="T" count="25000"></event>

    <tool_tip>
      Analyze fetch and ITLB behavior
    </tool_tip>

    <description>
      Use this configuration to find instruction fetches with poor
      L1 instruction cache locality and poor ITLB behavior.
    </description>

  </ebp>

</dc_configuration>

=== concocon/CodeAnalyst-3_4_18_0413-Public/src/ca/Configs/DCConfig/family15h/ibs_op_nb_cache.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Instruction-based sampling (IBS) data collection configuration
         Date:    28 June 2010
         Version: 1.1
         Processor: AMD family 15h
         Copyright (c) 2007-2010 Advanced Micro Devices, Inc.
                       All rights reserved.
 -->

<dc_configuration cpu_type="x86-64/family15h">

  <ebp name="IBS Op Northbridge Cache Access" mux_period="0">

	<event select="F201" mask="01" count="1000000"></event>
	<event select="F243" mask="01" count="1000000"></event>
	<event select="F244" mask="01" count="1000000"></event>
	<event select="F249" mask="01" count="1000000"></event>
	<event select="F24A" mask="01" count="1000000"></event>

    <tool_tip>
      Measure northbridge cache access performance using IBS Op
    </tool_tip>

    <description>
      Use this configuration to measure northbridge cache access performance 
      using IBS Op.
    </description>

  </ebp>

</dc_configuration>
